# Start up the backend and frontend services
version: "3"

services:
    backend:
        container_name: backend
        build:
            context: ./backend
        ports:
            - "3001:3001"

    frontend:
        container_name: frontend
        build:
            context: "."
        ports:
            - "3000:3000"
        depends_on:
            - backend
